### ISSUE TITLE
[Bug] Stuck on loading

### ISSUE THREAD

**Issue by headquarter8302** [SpikeHD/Dorion#256]
**Describe the bug**
After installing/upgrading Dorion, the client is stuck at the splash screen.

**To Reproduce**
1. Open the client.

**Expected behavior**
After the "DISCORDO" jingle, the screen should disappear and not interfere.

**Screenshots**
![image](https://github.com/user-attachments/assets/aed8406f-c5c0-4ced-9fbc-f9f54231d66c)

**System Info (please complete the following information):**
 - OS: Windows 11 Build 22621
 - Version: v6.0.1

**Additional context**
This happens both after an upgrade from the previous version (pre-v6.0.1), and after a clean reinstall

**Comment by SpikeHD** [comment]
Can you screenshot any errors in the DevTools console? And the contents of `%appdata%/dorion/logs/latest.log`? You can also try deleting `%appdata%/dorion/webdata` which will require a re-login

**Comment by headquarter8302** [comment]
![image](https://github.com/user-attachments/assets/7ed1a3f3-f430-4ad6-ac92-1f9358955775)

<details><summary>Log</summary>

```c
19:44:05.392  Waiting for definition...
19:44:05.398  shelter shelter is initializing...
19:44:05.426   Equicord   PluginManager  Starting plugins (stage Init)
19:44:05.427   Equicord   PluginManager  Starting plugin NoTrack
19:44:05.432 VM27:5  [TAURI] Couldn't find callback id 3357017953 in window. This happens when the app is reloaded while Rust is running an asynchronous operation.
(anonymous) @ VM27:5
19:44:05.442 VM29 app:1 [FAST CONNECT] wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream, encoding: json, version: 9
19:44:05.444 /app:48  [Deprecation] -ms-high-constrast is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
19:44:05.444 /app:48  [Deprecation] -ms-high-constrast is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
19:44:05.479   Equicord   MessageLoggerEnhanced  hii. no point in checking DataStore if. we already did up there ^^
19:44:05.595  __TAURI__ defined!
19:44:05.596   IPC custom protocol failed, Tauri will now use the postMessage interface instead TypeError: Cannot read properties of undefined (reading 'json')
    at VencordWeb:2:1205
    at Generator.next (<anonymous>)
    at VencordWeb:1:569
    at new Promise (<anonymous>)
    at c (VencordWeb:1:389)
    at window.fetch (VencordWeb:2:790)
    at Object.sendIpcMessage (<anonymous>:73:7)
    at Object.<anonymous> (<anonymous>:132:38)
    at action (<anonymous>:269:38)
    at <anonymous>:278:11
(anonymous) @ unknown
19:44:05.622   Equicord   WebpackInterceptor  Found Webpack module factory web.e93473d1dabe8710815a.js
19:44:05.929   Equicord   WebpackInterceptor  Main Webpack found in web.e93473d1dabe8710815a.js, initializing internal references to WebpackRequire
19:44:05.929   Equicord   WebpackInterceptor  Patching webpackChunkdiscord_app.push
19:44:06.131 web.e93473d1dabe8710815a.js:12 [ProcessUtilsElectron] setMemoryInformation not available.
19:44:06.342 web.e93473d1dabe8710815a.js:12 [default] [BUILD INFO] Release Channel: ptb, Build Number: 329302, Version Hash: 53cf6f0bf8b0617612985a5a861e7f8c6f049f70
19:44:06.343 web.e93473d1dabe8710815a.js:12 AppCrashedFatalReport: getLastCrash not supported.
19:44:06.463   Equicord   NoTrack  Disabling Sentry by erroring its WebpackInstance
19:44:06.463 VencordWeb:55  Uncaught Error: Sentry successfully disabled
    at Function.set (VencordWeb:55:19816)
    at sentry.958c305f88fe7b414204.js:453:37896
    at sentry.958c305f88fe7b414204.js:453:38435
19:44:06.464   Equicord   PluginManager  Starting plugins (stage DOMContentLoaded)
19:44:06.483  Patching postMessage...
19:44:06.483  Stopping here, we are in an iframe!
19:44:06.486  %cshelter%c background: linear-gradient(180deg, #2A3B4B 0%, #2BFAAC 343.17%); color: white; padding: 6px; border-radius: 4px;  shelter is initializing...
19:44:06.505  %c Equicord %c %c PluginManager  background: #a6d189; color: black; font-weight: bold; border-radius: 5px;  background: #a6d189; color: black; font-weight: bold; border-radius: 5px; Starting plugins (stage Init)
19:44:06.506  %c Equicord %c %c PluginManager  background: #a6d189; color: black; font-weight: bold; border-radius: 5px;  background: #a6d189; color: black; font-weight: bold; border-radius: 5px; Starting plugin NoTrack
19:44:06.507 VencordWeb:1343  Uncaught TypeError: Cannot read properties of undefined (reading 'addChangeListener')
19:44:06.507  %c Equicord %c %c PluginManager  background: #a6d189; color: black; font-weight: bold; border-radius: 5px;  background: #a6d189; color: black; font-weight: bold; border-radius: 5px; Starting plugins (stage DOMContentLoaded)
19:44:06.508  [Create LocalStorage] Done!
19:44:06.508 VM29 app:1 [FAST CONNECT] connected in 1066ms
19:44:06.537 /app:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://ptb.discord.com/assets/c1b53be672aac192a996.woff2
19:44:07.106 web.e93473d1dabe8710815a.js:12  [DEPRECATED] Please use `subscribeWithSelector` middleware
a @ web.e93473d1dabe8710815a.js:12
19:44:07.202 web.e93473d1dabe8710815a.js:12 [GatewaySocket] [CONNECT] wss://gateway.discord.gg, encoding: json, version: 9, compression: zlib-stream
19:44:07.202 web.e93473d1dabe8710815a.js:12 [GatewaySocket] [FAST CONNECT] successfully took over websocket, state: Object
19:44:07.202 web.e93473d1dabe8710815a.js:12 [GatewaySocket] [CONNECTED] wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream in 0 ms
19:44:08.245 VencordWeb:1  Uncaught (in promise) Error reading theme file: The system cannot find the file specified. (os error 2)
19:44:08.255  shelter shelter is initialized. took: 2855.4ms
19:44:08.833 web.e93473d1dabe8710815a.js:12 [GatewaySocket] [READY] took 1631ms, as d2004844e1b900f64b32144c068073fc
19:44:08.858 web.e93473d1dabe8710815a.js:12 [Flux] Dispatching CONNECTION_OPEN
19:44:08.862 web.e93473d1dabe8710815a.js:12 [DatabaseManager] removing database (user: 511031110076203018, database: undefined)
19:44:08.896   Equicord   PluginManager  Starting plugins (stage WebpackReady)
19:44:08.896   Equicord   PluginManager  Starting plugin BadgeAPI
19:44:08.897   Equicord   PluginManager  Starting plugin SupportHelper
19:44:08.897   Equicord   PluginManager  Starting plugin AlwaysExpandRoles
19:44:08.897   Equicord   PluginManager  Starting plugin MessageLinkEmbeds
19:44:08.897   Equicord   PluginManager  Starting plugin WebContextMenus
19:44:08.898   Equicord   PluginManager  Starting plugin WebKeybinds
19:44:08.904 web.e93473d1dabe8710815a.js:12 [GatewaySocket] [READY_SUPPLEMENTAL] took 1702ms
19:44:13.340 cdn.discordapp.com/changelogs/0/1275966022461165631/en-GB.json?x=8:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
19:49:51.968 @me:1  [Deprecation] -ms-high-constrast is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
19:49:51.968 @me:1  [Deprecation] -ms-high-constrast is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
19:49:52.034 @me:1  [Deprecation] Custom state pseudo classes have been changed from ":--emojiinputhorizontalpadding" to ":state(emojiinputhorizontalpadding)". See more here: https://github.com/w3c/csswg-drafts/issues/4805
```

</details>

Also, `dorion/webdata` doesn't exist here. I've checked the folder, it's not there:
![image](https://github.com/user-attachments/assets/292d2b9f-247b-4808-b183-b3c598be02ac)

**Comment by headquarter8302** [comment]
Another one to note, window controls, both Dorion's and Windows', doesn't appear. Let alone the window controls, the titlebar is missing, which was an intermittent issue in the previous releases but now it always happens.

I am not sure if this is a separate problem or not, so I'm not filing another issue just in case

**Comment by SpikeHD** [comment]
Looks like if Dorion fails to load whatever theme was selected, it just hard-stops the loading cycle. This is a bit annoying but if you delete `%appdata%/dorion/config.json` (or edit it and set `"theme" to `"none"`, which will preserve the rest of your settings) it should fix it.

**Comment by headquarter8302** [comment]
Changing the config did the trick, thank you!

It seems that you'll need to add checks for parts of the initial load

**Comment by SpikeHD** [comment]
Yep, that's been added in fc43e4c2942b4d06d758c3ff36a7910455e8c011, and will be available in the next release
